version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: file_parser_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/file_parser_db
    depends_on:
      - db

volumes:
  postgres_data: